name: Run Pytest

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pull-requests: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run pytest
        run: |
          pytest

      - name: Upload report and logs
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            reports/basic_report.html
            logs/app.log
      - name: Send email
        if: always()
        run: python utils/emailer.py
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
